# Generated by Django 5.1.3 on 2025-01-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
